name: Build and Push Astro SSR Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Compute lowercase repo name
        run: echo "REPO=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image
        run: docker build --build-arg DOTENV_PRIVATE_KEY_CI=${{ secrets.DOTENV_PRIVATE_KEY_CI }} -t ghcr.io/${{ env.REPO }}/ahmetalmaz:latest .

      - name: Push image
        run: docker push ghcr.io/${{ env.REPO }}/ahmetalmaz:latest

      - name: Send ntfy notification
        if: always()
        run: |
          STATUS="${{ job.status }}"
          curl -s -X POST \
            -H "Title: Astro SSR Build" \
            -H "Priority: high" \
            -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN }}" \
            -d "Build status: $STATUS" \
            "${{ secrets.NTFY_URL }}"
